# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25ae8c3ac0952e95d05992e5af11db94c26cebd0f5a89fba1c8778200b628df55000b68f6019f7afdf94718f358342853588881ae70f4cdeece1322bd20e501c

test:
  secret_key_base: 51f3ce741af559818a493b111a4a8d4ccdde67a50a319893211a7e6767def2ee84e1bd7208b59f9c95ed742f40a8a00bab9449e0f3319537bfcd3d120b95f3bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
